# Generated by Django 5.1.1 on 2024-10-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tutorprofile_rating_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.CharField(default='github.com', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='linked_in',
            field=models.CharField(default='linkedin.com', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='0700***000', max_length=10),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='location',
            field=models.CharField(default='Nairobi, Kenya', max_length=255),
        ),
    ]
