# Generated by Django 5.1.1 on 2024-10-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_location_profile_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='location',
            field=models.CharField(default='Online', max_length=255),
        ),
    ]
