# Generated by Django 5.1.1 on 2024-10-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_tutorprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='media/profile/avatar.png', upload_to='profile_pics/'),
        ),
    ]
