# Generated by Django 5.1.1 on 2024-10-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.CharField(default='github.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='linked_in',
            field=models.CharField(default='linkedin.com', max_length=255),
        ),
    ]
